#spring.application.name=

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=UdemyTest;encrypt=true;trustServerCertificate=true
spring.datasource.username=Roshan
spring.datasource.password=passw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

# Customizing the app information
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.swagger-ui.enabled=true
#springdoc.api-docs.path=/v3/api-docs
#springdoc.api-docs.enabled=true
#
## Customizing the documentation
#springdoc.packagesToScan=com.projects.demo.controller
##springdoc.packagesToScan=com.projects.demo.controller,com.projects.demo.config
#springdoc.pathsToMatch=/api/**
#
## If this is present, it might cause issues with springdoc-openapi
##spring.mvc.pathmatch.matching-strategy=ant-path-matcher



#spring.security.user.name=roshan
#spring.security.user.password=passw0rd
server.port=9090