#spring.application.name=

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=UdemyTest;encrypt=true;trustServerCertificate=true
spring.datasource.username=Roshan
spring.datasource.password=passw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

# Customizing the app information
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.swagger-ui.enabled=true
#springdoc.api-docs.path=/v3/api-docs
#springdoc.api-docs.enabled=true
#
## Customizing the documentation
#springdoc.packagesToScan=com.projects.demo.controller
##springdoc.packagesToScan=com.projects.demo.controller,com.projects.demo.config
#springdoc.pathsToMatch=/api/**
#
## If this is present, it might cause issues with springdoc-openapi
##spring.mvc.pathmatch.matching-strategy=ant-path-matcher



#spring.security.user.name=roshan
#spring.security.user.password=passw0rd
server.port=9090

#jwt.secret=adminkeyforjwt1234567890adminkeyforjwt

jwt.secret=adryl8GfrlYovsbJw9yLkSURrzjEm2Al8xCAo1zLHsk=

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=428739142060-1u1m6hasg8aj70ejhgfdk37bii80hngq.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

#spring.security.oauth2.client.registration.google.scope=openid,profile,email
#spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.google.client-name=Google
#
#spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
#spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
#spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
#spring.security.oauth2.client.provider.google.user-name-attribute=sub


# GitHub OAuth2 Configuration
spring.security.oauth2.client.registration.github.client-id=Ov23liZFdckypXEVCIKf
spring.security.oauth2.client.registration.github.client-secret=89fcaa3f5f3d4dbf9626dec7fa7cd2b55db312fb