--insert into dbo.Student(rollno,name,marks) values (101,"Rahul",79);
--insert into dbo.Student(rollno,name,marks) values (102,"Roshan",80);
--insert into dbo.Student(rollno,name,marks) values (103,"Bauwaa",81);
--
----Select * from dbo.Student